const express=require('express')
const router=express.Router()

const Users =require('../../controllers/user/user')
const {decodeJwtToken} = require("../../middlewares/helper")
router.post('/signup',Users.signup)
router.post("/login", Users.login)
router.post("/forgot-password-send-otp",decodeJwtToken, Users.forgotPassSendOtp)
router.post("/verify-otp", decodeJwtToken, Users.verifyotp)
router.post("/reset-password", decodeJwtToken, Users.resetPassword)
router.post("/update-profile", decodeJwtToken, Users.updateprofile)
router.post("/search-friend-list", decodeJwtToken, Users.searchFriendList)
router.post("/view-friend-profile", Users.viewFriendProfile)
router.post("/send-friend-request", decodeJwtToken, Users.sendFriendRequest)
router.get("/friend-list", decodeJwtToken, Users.friendList)
router.get("/friend-request-list", decodeJwtToken, Users.friendRequestList)
router.post("/accept-friend-request", decodeJwtToken, Users.acceptFriendRequest)
router.post("/reject-friend-request", decodeJwtToken, Users.rejectFriendReuest)
router.post("/refresh-token", Users.refreshToken)
router.post("/remove-friend", decodeJwtToken, Users.removeFriend)
module.exports=router
